url: https://kotonyan.github.io/Kira_Star/
baseurl: /Kira_Star/

# Site settings
title: Kira Star Studio
email: kotonyan_carnival@qq.com
description: "福州绮罗星文化传媒有限公司成立于2018年底，主营游戏相关的翻译本地化、文本撰写、宣传推广等业务。"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: weibo
    url: 
  - title: twitter
    url:
  - title: wechat
    url: Kotonyan
  - title: mail
    url: kotonyan_carnival@qq.com
  - title: phone
    url: （+86）18516340877

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
